### ISSUE TITLE
Other functions

### ISSUE THREAD

**Issue by MasterPolska123** [WolfgangSenff/GodotFirebase#13]
As far as possible, add other functions such as logging in and registering in with all FireBase-supported methods and restoring the user account password

**Comment by WolfgangSenff** [comment]
I'm not sure what you mean. You can login and all that stuff just fine right now, as far as my tests can tell.

**Comment by MasterPolska123** [comment]
I mean login through other websites listed on

https://console.firebase.google.com/project/<projest-name>/authentication/providers

for example facebook. You know - you can login to many websites via google and facebook. And the ability to change the password through the game. I would be very grateful. I will soon do a Polish tutorial on this add-on for your YouTube channel.

**Comment by WolfgangSenff** [comment]
Ah I see. I will consider implementing it, but I'm in the middle of a big move (as in a physical move to a new apartment). I'll look into it when I'm settled a bit next month, most likely. It's a good suggestion though, so leaving it open.

**Comment by WolfgangSenff** [comment]
Oh, and I should mention, I do accept PRs. Feel free to give it a shot. :)

**Comment by MasterPolska123** [comment]
One more thing... could you add comments to the scripts (for example GDFirebase / FirebaseStorage.gd) explaining what (in 'upload' and 'download' and 'upload' functions) are the values like like 'obj', 'folder_path', 'file_name'.
Good luck with this Godot addon. Is fantastic.

Translated with Google Translate

**Comment by japalekhin** [comment]
@WolfgangSenff hey man, any word on FB/G login?

**Comment by c0ppo** [comment]
@WolfgangSenff 

Hi. Is this plugin still in active development?
Please provide for something like patreon, so people like me who are REALLY interested in you completing the plugin + documentation can donate.

I would donate for a completed plugin without any hesitation. And since this is the only plugin that supports all platforms, I think you will find that there are more people like me.

Best regards

**Comment by lentsius-bark** [comment]
I support the words of the previous poster. A plugin such as this one is a key component of many potential projects.

**Comment by WolfgangSenff** [comment]
I have provided them before - must not be on the readme, doh! My mistake. There are limitations though - for instance, storage cannot be implemented (it's not really a Firebase product - it's a loose wrapping around Google Cloud stuff, and there's no REST API for it, or it's extremely convoluted; I'd consider researching it again though if it's a game-changer). I'll be adding my Patreon/Ko-fi presently.

**Comment by WolfgangSenff** [comment]
I have updated the readme. I will attempt to update this plugin again over the upcoming weekend or so, in order to account for the remaining user authentication needs such as changing password and such. That said, it already supports Facebook and other logins, as far as I can tell - you just need to have them setup correctly in the Authentication tab in the Firebase Console. I'm closing this for now in order that you folks can post more targeted questions/issues - if you feel there are still any after this weekend, please do let me know, happy to work on this.
