### ISSUE TITLE
Firebase storage 

### ISSUE THREAD

**Issue by Saxito** [WolfgangSenff/GodotFirebase#23]
Hi, 

I just want to know if it's works for firebase storage ans if the plugin works on android 

thanks

**Comment by WolfgangSenff** [comment]
Firebase Storage does not have a REST API that is readily available, unfortunately, so that's out. There's a way to integrate it through Google Cloud, but is not part of this plugin.

This plugin is usable across all possible platforms, with only the possible exception of HTML; the only reason I do not know if it works with HTML is because HTML uploading has never worked for me, and nothing I do seems to make it work - I have had people test my projects by uploading on their own and it does seem to work, however. But because I cannot verify HTML specifically, I mark this as usable on all other platforms.
