### ISSUE TITLE
[FATAL!!! URGENT Security Issue] Firebase Config file is loaded in hard code way...

### ISSUE THREAD

**Issue by JOELwindows7** [WolfgangSenff/GodotFirebase#27]
# And that creates big security problem.
- This plugin reads the config in `Firebase.gd`, which means hard coded, instead of doing so from separate `.gitignore`-able file
- Developer will forgot to `.gitignore` this,
- which can cause the private keys (like **Google API keys**) in that config spread wild and could be abused if they decided to make their game anything source available (Open Source, and so), and uploaded it to public like GitHub, GitLab, or any version control Git thingy.
- This could jeopardize entire Firebase project! anyone could hack and mess around with that.

# How to fix this? **LOAD FROM SEPARATE FILE!**
- Create better setup way using a window that let user insert the config data into each LineEdit.
- After clicking save, the window will save it on a separate setup save file.
- `.gitignore` will also be created ignoring the setup save file.

# Workaround 
let's say you are Open Source and upload to GitHub. I use [GitHub Desktop](https://desktop.github.com ) to do Git easily with UI.

- just `.gitignore` `Firebase.gd` once you are going to use it.
- or if you don't want to immediately ignore `Firebase.gd` (because other cloners could get script not found error during project load), maybe don't fill the config just yet before the fix comes.

**Comment by fenix-hub** [comment]
Hi, I'm not the owner / creator of this repository, but recently I've pushed some changes and I'll do the same in the future for sure.
Just wanted to point out that currently API keys are not hardcoded. The dictionary inside the `Firebase.gd` is just a placeholder and it is not mandatory to fulfill.
With my last commit the things you describe could be already achieved, even though there is not an explaination nor a tutorial yet.
I've moved each necessary key to the `override.cfg` file, which is a file that can be .gitignor-ed, and each key can be inserted directly in the Project Settings via the editor. For the technical part about `override.cfg`s files I just suggest to you [this reading](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html).

Anyway, yes: there still are some things that can be improved as you suggested:
- Removing the `config`  dictionary from `Firebase.gd` since it could lead to a missbehaviour from new users pushing their private datas
- Make the README (and the documentation) more explicit about how to handle this datas in general and specifically in this plugin
- Create an automatic .gitignore that is placed in the root of the project, eventually the standard .gitignore used for Godot Projects
- Add some informations about how to add all the API keys with the current setup, which honestly I think it is the better way both for a Firebase handling of API keys and for a Godot project API keys handling in general (using what the Engine actually offers and don't do too many workarounds)

**Comment by WolfgangSenff** [comment]
Actually, you're both wrong. 🤣 In Firebase, the keys are often totally public. You should be properly securing your app through security rules, *not* the config file. See Doug Stevenson's (one of Firebase's project leads) answer here: https://stackoverflow.com/questions/52100690/should-i-hide-firebase-api-keys-into-backend-not-due-to-data-security-but-proje

This is the same advice they give all over the internet.
