### ISSUE TITLE
Can't get document with .get()

### ISSUE THREAD

**Issue by mjfgames** [WolfgangSenff/GodotFirebase#65]
Hi, I can't get document from collection, which already exists (I created document on Firebase side)
Collection name is 'allusers' and document name is 'admin'

```
func _on_Button2_pressed():
	# get existing document
	var coll = Firebase.Firestore.collection('allusers')
	var doc = coll.get('admin')
	print(doc) # prints Null
```
I noticed that in firestore.gd, `collections` variable is also Null:

```
func collection(path : String) -> FirestoreCollection:
		if !collections.has(path):
				var coll : FirestoreCollection = FirestoreCollection.new()
				coll.extended_url = extended_url
				coll.base_url = base_url
				coll.config = config
				coll.auth = auth
				coll.collection_name = path
				print(collections)                            # prints Null
				collections[path] = coll
				add_child(coll)
				return coll
		else:
				return collections[path]
```

which is incorrect as collection and all data exists.

**Comment by fenix-hub** [comment]
Hi @mjfgames ,
The method you are using to get a document is not completely correct.
If you followed the example in the documentation, it actually is incorrect and we will fix it immediately.

When you call the `.get()` function on a collection the document is not immediately returned, since an HTTPRequest needs to be issued, and you need to wait for it to return.
So, to properly get a document, you have two options:
1. call the `.get()` function and than yield for the collection to return it with a signal
```python
var collection : FirestoreCollectoin = Firebase.Firestore.collection("allusers")
collection.get("admin")
var document : FirestoreDocument = yield(collection, "get_document")
print(document) # -> will not be Null
```
2. Connect a signal to the collection and get the document separately
```python
var collection : FirestoreCollectoin = Firebase.Firestore.collection("allusers")
collection.connect("get_document",self,"_on_get_document")
collection.get("admin")

[...]
func _on_get_document(document : FirestoreDocument) -> void:
print(document) # -> will not be Null
```
Also, since we have added some updates, please pull the latest version from the repository and add them to your project. I'd suggest you to not use the AssetLib for now, since it is not updated.

Thank you very much, I'll leave the issue open if you have any other quesiton :)

**Comment by mjfgames** [comment]
Okay, after implementing code it still didn't work, but I figured out there was a bug in `func on_pusher_request_complete(result, response_code, headers, body)
` where `request = REQUESTS.NONE` was placed in wrong line. But as you said, I updated to latest version and it is fixed and works fine now. Thank you very much for help!
